spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: lHgfP?EsP4eH
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

knife4j:
  enable: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

#WEB配置
server:
  port: 8080
  servlet:
    context-path: /text
    session:
      timeout: 60

